services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - "3001:3000"
    env_file:
      - ./server/.env
    depends_on:
      - db
    command: >
      sh -c "npm run migration:run && npm run start:dev"

  client:
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - server

networks:
  emarket:
    name: emarket
    driver: bridge

volumes:
  pgdata: